spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/food?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
